packages:
  - features/*/contracts
  - features/*/domain
  - features/*/ui
  - libs/*
  - apps/*
  - tools/*

ignoredBuiltDependencies:
  - '@nestjs/core'
  - '@scarf/scarf'
  - core-js

onlyBuiltDependencies:
  - '@swc/core'
  - bcrypt
  - esbuild
  - mongodb-memory-server
  - protobufjs

overrides:
  '@conventional-changelog/git-client': ^2

shamefullyHoist: true
