shamefullyHoist: true

packages:
    - features/*/contracts
    - features/*/domain
    - features/*/ui
    - libs/*
    - apps/*
    - tools/*

ignoredBuiltDependencies:
    - '@nestjs/core'
    - '@scarf/scarf'

onlyBuiltDependencies:
    - '@swc/core'
    - esbuild
    - protobufjs
