packages:
  - features/*/contracts
  - features/*/domain
  - features/*/ui
  - libs/*
  - apps/*
  - tools/*

ignoredBuiltDependencies:
  - '@nestjs/core'
  - '@scarf/scarf'

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - mongodb-memory-server
  - protobufjs

shamefullyHoist: true

overrides:
  '@conventional-changelog/git-client': ^2